-- batch 1779091288421170107
BEGIN;
INSERT INTO weather_observations_raw (message_id, source, continent, country, region, city, event_time, created_at, temperature, humidity, wind_speed, payload_json) VALUES ('collector:south_india-1779091288405-2', 'collector:south_india', 'Asia', 'India', 'south_india', 'Bangalore', to_timestamp(1779091288405 / 1000.0), to_timestamp(1779091288405 / 1000.0), 33.2, 39, 6.7, '{"created_at":1779091288405,"message_id":"collector:south_india-1779091288405-2","message_type":"weather.packet","payload":{"city":"Bangalore","continent":"Asia","country":"India","humidity":39.0,"region":"south_india","temperature":33.2,"timestamp":1779091288405,"wind_speed":6.7},"route":"south_india_aggregator","schema_version":1,"source":"collector:south_india"}') ON CONFLICT (message_id) DO NOTHING;
INSERT INTO weather_city_minute_aggregates (bucket_start, continent, country, region, city, observation_count, min_temperature, max_temperature, avg_temperature, avg_humidity, avg_wind_speed) VALUES (to_timestamp(1779091260000 / 1000.0), 'Asia', 'India', 'south_india', 'Bangalore', 1, 33.2, 33.2, 33.2, 39, 6.7) ON CONFLICT (bucket_start, continent, country, region, city) DO UPDATE SET observation_count = EXCLUDED.observation_count, min_temperature = LEAST(weather_city_minute_aggregates.min_temperature, EXCLUDED.min_temperature), max_temperature = GREATEST(weather_city_minute_aggregates.max_temperature, EXCLUDED.max_temperature), avg_temperature = EXCLUDED.avg_temperature, avg_humidity = EXCLUDED.avg_humidity, avg_wind_speed = EXCLUDED.avg_wind_speed;
COMMIT;

-- batch 1779247241996248772
BEGIN;
INSERT INTO weather_observations_raw (message_id, source, continent, country, region, city, event_time, created_at, temperature, humidity, wind_speed, payload_json) VALUES ('collector:north_india-1779247241822-7', 'collector:north_india', 'Asia', 'India', 'north_india', 'Delhi', to_timestamp(1779247241805 / 1000.0), to_timestamp(1779247241822 / 1000.0), 35.5, 23, 8.1, '{"created_at":1779247241822,"message_id":"collector:north_india-1779247241822-7","message_type":"weather.packet","payload":{"city":"Delhi","continent":"Asia","country":"India","humidity":23.0,"region":"north_india","temperature":35.5,"timestamp":1779247241805,"wind_speed":8.1},"route":"north_india_aggregator","schema_version":1,"source":"collector:north_india"}') ON CONFLICT (message_id) DO NOTHING;
INSERT INTO weather_observations_raw (message_id, source, continent, country, region, city, event_time, created_at, temperature, humidity, wind_speed, payload_json) VALUES ('collector:americas-1779247241906-8', 'collector:americas', 'Americas', 'USA', 'americas', 'Los Angeles', to_timestamp(1779247241813 / 1000.0), to_timestamp(1779247241906 / 1000.0), 21.2, 43, 6.8, '{"created_at":1779247241906,"message_id":"collector:americas-1779247241906-8","message_type":"weather.packet","payload":{"city":"Los Angeles","continent":"Americas","country":"USA","humidity":43.0,"region":"americas","temperature":21.2,"timestamp":1779247241813,"wind_speed":6.8},"route":"americas_aggregator","schema_version":1,"source":"collector:americas"}') ON CONFLICT (message_id) DO NOTHING;
INSERT INTO weather_observations_raw (message_id, source, continent, country, region, city, event_time, created_at, temperature, humidity, wind_speed, payload_json) VALUES ('collector:south_india-1779247241920-7', 'collector:south_india', 'Asia', 'India', 'south_india', 'Bangalore', to_timestamp(1779247241895 / 1000.0), to_timestamp(1779247241920 / 1000.0), 24, 79, 12, '{"created_at":1779247241920,"message_id":"collector:south_india-1779247241920-7","message_type":"weather.packet","payload":{"city":"Bangalore","continent":"Asia","country":"India","humidity":79.0,"region":"south_india","temperature":24.0,"timestamp":1779247241895,"wind_speed":12.0},"route":"south_india_aggregator","schema_version":1,"source":"collector:south_india"}') ON CONFLICT (message_id) DO NOTHING;
INSERT INTO weather_city_minute_aggregates (bucket_start, continent, country, region, city, observation_count, min_temperature, max_temperature, avg_temperature, avg_humidity, avg_wind_speed) VALUES (to_timestamp(1779247200000 / 1000.0), 'Americas', 'USA', 'americas', 'Los Angeles', 1, 21.2, 21.2, 21.2, 43, 6.8) ON CONFLICT (bucket_start, continent, country, region, city) DO UPDATE SET observation_count = EXCLUDED.observation_count, min_temperature = LEAST(weather_city_minute_aggregates.min_temperature, EXCLUDED.min_temperature), max_temperature = GREATEST(weather_city_minute_aggregates.max_temperature, EXCLUDED.max_temperature), avg_temperature = EXCLUDED.avg_temperature, avg_humidity = EXCLUDED.avg_humidity, avg_wind_speed = EXCLUDED.avg_wind_speed;
INSERT INTO weather_city_minute_aggregates (bucket_start, continent, country, region, city, observation_count, min_temperature, max_temperature, avg_temperature, avg_humidity, avg_wind_speed) VALUES (to_timestamp(1779247200000 / 1000.0), 'Asia', 'India', 'north_india', 'Delhi', 1, 35.5, 35.5, 35.5, 23, 8.1) ON CONFLICT (bucket_start, continent, country, region, city) DO UPDATE SET observation_count = EXCLUDED.observation_count, min_temperature = LEAST(weather_city_minute_aggregates.min_temperature, EXCLUDED.min_temperature), max_temperature = GREATEST(weather_city_minute_aggregates.max_temperature, EXCLUDED.max_temperature), avg_temperature = EXCLUDED.avg_temperature, avg_humidity = EXCLUDED.avg_humidity, avg_wind_speed = EXCLUDED.avg_wind_speed;
INSERT INTO weather_city_minute_aggregates (bucket_start, continent, country, region, city, observation_count, min_temperature, max_temperature, avg_temperature, avg_humidity, avg_wind_speed) VALUES (to_timestamp(1779247200000 / 1000.0), 'Asia', 'India', 'south_india', 'Bangalore', 1, 24, 24, 24, 79, 12) ON CONFLICT (bucket_start, continent, country, region, city) DO UPDATE SET observation_count = EXCLUDED.observation_count, min_temperature = LEAST(weather_city_minute_aggregates.min_temperature, EXCLUDED.min_temperature), max_temperature = GREATEST(weather_city_minute_aggregates.max_temperature, EXCLUDED.max_temperature), avg_temperature = EXCLUDED.avg_temperature, avg_humidity = EXCLUDED.avg_humidity, avg_wind_speed = EXCLUDED.avg_wind_speed;
COMMIT;

